Fix reverse accessor clash:
https://stackoverflow.com/a/41595447/3405291

```
/usr/local/bin/docker-compose exec -T web python manage.py makemigrations ads

SystemCheckError: System check identified some issues:

ERRORS:
ads.Category.created_by: (fields.E304) Reverse accessor for 'Category.created_by' clashes with reverse accessor for 'Category.user'.
        HINT: Add or change a related_name argument to the definition for 'Category.created_by' or 'Category.user'.
files.Category.user: (fields.E304) Reverse accessor for 'Category.user' clashes with reverse accessor for 'Category.created_by'.
        HINT: Add or change a related_name argument to the definition for 'Category.user' or 'Category.created_by'.

```